{% set name = "rptools" %}
{% set version = "6.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rptools/archive/{{ version }}.tar.gz
  sha256: 8803ca1996f805fa01a8e83eaba2c0459929280124ff19b29684bf2629b6ce39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.11a0
    - brs_utils
    - cobra >=0.26.3
    - timeout-decorator
    - rdkit
    - python-libsbml
    - pandas <2.0
    - scipy
    - equilibrator-api
    - equilibrator-cache >=0.5.4
    - colored
    - networkx >=2.5
    - filetype
    - rr_cache >=3.3.0
    - rxn_rebuild >=3.1.4
    - chemlite
    - h5py
    - xgboost
    - bs4

test:
  source_files:
    - tests
  imports:
    - rptools
  commands:
    - python -m rptools --help

about:
  home: https://github.com/brsynth/rptools
  summary: Suite of tools that work on rpSBML data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
