{% set name = "rptools" %}
{% set version = "6.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rptools/archive/{{ version }}.tar.gz
  sha256: 074512c9fc3a27d156689f6cc7b665515215037ca14f36b11ae0f3b99ae74184

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.7,<=3.10
    - pip
  run:
    - python >=3.7,<=3.10
    - brs_utils
    - cobra >=0.26.3
    - timeout-decorator
    - rdkit
    - python-libsbml
    - pandas
    - scipy
    - equilibrator-api
    - equilibrator-cache >=0.5.4
    - colored
    - networkx >=2.5
    - filetype
    - rr_cache >=3.1.1
    - rxn_rebuild
    - chemlite
    - h5py
    - xgboost
    - bs4

test:
  source_files:
    - tests
  imports:
    - rptools
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  commands:
    - python -m rptools --help
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/rptools
  summary: Suite of tools that work on rpSBML data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - kenza12
