{% set name = "rptools" %}
{% set version = "6.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rptools/archive/{{ version }}.tar.gz
  sha256: aa8f447dffbae685613a89740f9effba3bda06a99d7b2b0c6d4d3f7a825a9a64

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.11a0
    - brs_utils
    - cobra >=0.26.3
    - timeout-decorator
    - rdkit
    - python-libsbml
    - pandas
    - scipy
    - equilibrator-api
    - equilibrator-cache >=0.5.4
    - colored
    - networkx >=2.5
    - filetype
    - rr_cache >=3.1.1
    - rxn_rebuild
    - chemlite
    - h5py
    - xgboost
    - bs4

test:
  source_files:
    - tests
  imports:
    - rptools
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
    - python {{ python_min }}
  commands:
    - python -m rptools --help
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/rptools
  summary: Suite of tools that work on rpSBML data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - kenza12
